"""Constants for the Foreca integration."""
from datetime import timedelta
from typing import Final

DOMAIN: Final = "foreca_ha"
SCAN_INTERVAL: Final = timedelta(minutes=30)
BASE_URL: Final = "https://www.foreca.fi/"
LAKE_TEMP_URL: Final = "https://www.foreca.fi/api/lake-temp"
ICE_URL: Final = "https://www.foreca.fi/api/ice"
HEADERS: Final = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

# Mapping Finnish labels to internal keys
LABEL_MAP: Final = {
    "Ulkopukeutuminen": "clothing",
    "Ilmanlaatu": "aqi",
    "UV-indeksi": "uv",
    "Säävaroitukset": "warnings",
}

LAKE_TEMP_STATIONS: Final = [
    "Ala-Rieveli",
    "Haukivesi",
    "Hinjärvi",
    "Inari",
    "Jääsjärvi",
    "Kallavesi",
    "Kevojärvi",
    "Kilpisjärvi",
    "Kitusjärvi",
    "Konnevesi",
    "Kuivajärvi",
    "Kukkolankoski",
    "Kyyvesi",
    "Lappajärvi",
    "Lohjanjärvi",
    "Längelmävesi",
    "NuasjärviVuokatti",
    "Näsijärvi",
    "Oijärvi",
    "Oulankajoki",
    "Oulujärvi",
    "Ounasjärvi",
    "Pesiöjärvi",
    "Pielavesi",
    "Pielinen",
    "Pyhäselkä",
    "Päijänne",
    "Pääjärvi",
    "Saimaa",
    "Säkylän Pyhäjärvi",
    "Tuusulanjärvi",
    "Unari",
]

ICE_THICKNESS_STATIONS: Final = [
    "Hiidenvesi, Nummela",
    "Haukivesi, Oravi",
    "Iisvesi, Suonenjoki",
    "Inari, Nellim",
    "Inari, Paksuvuono",
    "Jääsjärvi, Hartola",
    "Kallavesi, Itkonniemi",
    "Kevojärvi, Utsjoki",
    "Kilpisjärvi",
    "Konnevesi, Näreselkä",
    "Kuivajärvi, Saari, Tammela",
    "Kuuhankavesi, Hankasalmi",
    "Kyyvesi, Haukivuori",
    "Lammasjärvi, Kuhmo",
    "Lappajärvi, Halkosaari",
    "Lappalanjärvi",
    "Lestijärvi",
    "Lokka",
    "Längelmävesi, Kaivanto",
    "Muojärvi, Kuusamo",
    "Näsijärvi, Naistenlahti, Tampere",
    "Oijärvi",
    "Oulujärvi, Manamansalo",
    "Oulujärvi, Paltaselkä",
    "Ounasjärvi, Enontekiö",
    "Palovesi, Murole",
    "Pesiöjärvi, Suomussalmi",
    "Petäjävesi, Karikkoselkä",
    "Pielavesi, Säviä",
    "Pielinen, Nurmes",
    "Pitkäjärvi, Espoo",
    "Pyhäjärvi, Pyhäsalmi",
    "Pyhäjärvi, Säkylä",
    "Pyhäselkä, Roukalahti",
    "Päijänne, Sysmä, Verkkosaaret",
    "Päijänne, Tehin selkä",
    "Pääjärvi, Karstula",
    "Pääjärvi, Lammi",
    "Saimaa, Lauritsala",
    "Simpelejärvi, Parikkala",
    "Sääksjärvi, Kokemäki",
    "Tornionjoki, Pello",
    "Tornionjoki, Tornio",
    "Tuusulanjärvi",
    "Tyräjärvi, Tyrämäki",
    "Unari, Sodankylä",
]

SNOW_DEPTH_STATIONS: Final = [
    "Asikkala Pulkkilanharju",
    "Espoo Nuuksio",
    "Haapavesi Mustikkamäki",
    "Halli lentoasema",
    "Hattula Lepaa",
    "Helsinki Kaisaniemi",
    "Helsinki Kumpula",
    "Helsinki Majakka",
    "Helsinki-Vantaan lentoasema",
    "Hirvihaara",
    "Huittinen Sallila",
    "Hyvinkää Hyvinkäänkylä",
    "Hämeenlinna Pirttikoski",
    "Ilomantsi Mekrijärvi",
    "Inari Angeli",
    "Inari Kaamanen",
    "Inari Raja-Jooseppi",
    "Inari Saariselkä Kaunispää",
    "Inari Seipäjärvi",
    "Inari Väylä",
    "Inkoo Bågaskär",
    "Jomala Jomalaby",
    "Juuka Niemelä",
    "Juupajoki Hyytiälä",
    "Jyväskylä lentoasema",
    "Jämsä Saarijärvi",
    "Kajaani lentoasema",
    "Kalajoki Himanka",
    "Kankaanpää Niinisalo",
    "Karijoki Alakylä",
    "Kauhava lentokenttä",
    "Kemiönsaari Kemi",
    "Kittilä Kenttärova",
    "Kittilä Kirkonkylä",
    "Kittilä lentoasema",
    "Kittilä Pokka",
    "Kittilä Pulju",
    "Kokemäki Tulkkila",
    "Kokkola Tankar",
    "Konnevesi Kirkonkylä",
    "Kouvola Anjala",
    "Kouvola Utti",
    "Kristiinankaupunki Majakka",
    "Kruunupyy lentoasema",
    "Kuhmo Kalliojoki",
    "Kuopio Maaninka",
    "Kuopio Rissala lentoasema",
    "Kuusamo Kiutaköngäs",
    "Kuusamo lentoasema",
    "Kuusamo Ruka",
    "Kyyjärvi Kirkonkylä",
    "Lahti Laune",
    "Lappeenranta lentoasema",
    "Lapua Saarenkangas",
    "Lieksa Lampela",
    "Liperi Joensuu lentoasema",
    "Lohja Leppäkorpi",
    "Lohja Porla",
    "Loviisa Orrengrund",
    "Lumparland Långnäs",
    "Maarianhamina lentoasema",
    "Mikkeli lentoasema",
    "Muonio Kirkonkylä",
    "Muonio Laukukero",
    "Multia Karhila",
    "Oulu lentoasema",
    "Oulu Vihreäsaari",
    "Outokumpu Viuruniemi",
    "Parainen Fagerholm",
    "Parainen Utö",
    "Pello Kirkonkylä",
    "Pelkosenniemi Pyhätunturi",
    "Pori lentoasema",
    "Porvoo Emäsalo",
    "Porvoo Kilpilahti",
    "Pudasjärvi Sarakylä",
    "Pudasjärvi lentokenttä",
    "Puumala Kirkonkylä",
    "Pyhäjärvi Ojakylä",
    "Puolanka Paljakka",
    "Raahe Lapaluoto",
    "Rauma Kylmäpihlaja",
    "Rautavaara Ylä-Luosta",
    "Rovaniemi Apukka",
    "Rovaniemi lentoasema",
    "Salla Kirkonkylä",
    "Salla Naruska",
    "Salla Värriötunturi",
    "Salo Kärkkä",
    "Savonlinna lentoasema",
    "Savonlinna Punkaharju",
    "Seinäjoki Pelmaa",
    "Siikajoki Ruukki",
    "Siilinjärvi Kirkonkylä",
    "Siuntio Sjundby",
    "Sodankylä Lokka",
    "Sodankylä Tähtelä",
    "Sotkamo Kuolaniemi",
    "Suomussalmi Pesiö",
    "Sysmä Särkilahti",
    "Tampere-Pirkkala lentoasema",
    "Tohmajärvi Kemie",
    "Tornio Kaakkuri",
    "Turun lentoasema",
    "Utsjoki Kevo",
    "Utsjoki Nuorgam",
    "Vaala Pelso",
    "Vaasan lentoasema",
    "Valtimo Kirkonkylä",
    "Varkaus Kosulanniemi",
    "Vesanto Kirkonkylä",
    "Vihti Hiiskula",
    "Viitasaari Kirkonkylä",
    "Virojoki Harju",
    "Ylitornio Meltosjärvi",
    "Ähtäri Ähtärinranta"
]